# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identyfikator')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='tytuł')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('poster', models.URLField(blank=True, verbose_name='plakat')),
                ('production', models.CharField(blank=True, max_length=255, verbose_name='produkcja')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='gatunek')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='czas trwania')),
                ('yt_video_id', models.CharField(blank=True, max_length=255, verbose_name='YouTube video id')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'filmy',
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identyfikator')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pckisz_pl_cache.Movie', verbose_name='film')),
            ],
            options={
                'verbose_name': 'projekcje',
                'verbose_name_plural': 'projekcje',
                'ordering': ('start', 'movie'),
            },
        ),
    ]
