# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pckisz_pl_cache', '0002_screening_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='end',
            field=models.DateTimeField(blank=True, help_text='To pole jest automatycznie uzupełnione na podstawie pola start oraz długości filmu.', null=True, verbose_name='end'),
        ),
    ]
