# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pckisz_pl_cache', '0003_screening_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='end',
            field=models.DateTimeField(blank=True, help_text='To pole zostało automatycznie uzupełnione na podstawie pola start oraz długości filmu.', null=True, verbose_name='koniec'),
        ),
    ]
